receivers:
  otlp:
    protocols:
      grpc:
  jaeger:
    protocols:
      grpc:
  zipkin:

exporters:
  otlp:
    endpoint: "otel-collector:4317"
    insecure: true
  logging:
    loglevel: debug

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [batch]
      exporters: [otlp, logging]
